api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    eager_loading:
        max_joins: 400
    collection:
        order_parameter_name: '_order' # the URL query parameter to use is now "_order"