<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210203082513 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE article (id INT AUTO_INCREMENT NOT NULL, categorie_id INT NOT NULL, titre VARCHAR(255) NOT NULL, contenu LONGTEXT NOT NULL, date DATE DEFAULT NULL, url VARCHAR(255) NOT NULL, extrait VARCHAR(255) NOT NULL, image VARCHAR(255) DEFAULT NULL, INDEX IDX_23A0E66BCF5E72D (categorie_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE booking (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, listing_id INT DEFAULT NULL, start DATETIME NOT NULL, end DATETIME NOT NULL, start_time DATETIME NOT NULL, end_time DATETIME NOT NULL, status SMALLINT NOT NULL, validated TINYINT(1) NOT NULL, amount NUMERIC(8, 0) DEFAULT NULL, amount_fee_as_asker NUMERIC(8, 0) DEFAULT NULL, amount_fee_as_offerer NUMERIC(8, 0) DEFAULT NULL, amount_total NUMERIC(8, 0) DEFAULT NULL, cancellation_policy SMALLINT NOT NULL, new_booking_at DATETIME DEFAULT NULL, payed_booking_at DATETIME DEFAULT NULL, refused_booking_at DATETIME DEFAULT NULL, canceled_asker_booking_at DATETIME DEFAULT NULL, alerted_expiring TINYINT(1) NOT NULL, alerted_imminent TINYINT(1) NOT NULL, message TEXT NOT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, INDEX IDX_E00CEDDEA76ED395 (user_id), INDEX end_idx (end), INDEX status_idx (status), INDEX alerted_expiring_idx (alerted_expiring), INDEX updated_at_idx (updatedAt), INDEX IDX_E00CEDDED4619D1A (listing_id), INDEX start_time_idx (start_time), INDEX validated_idx (validated), INDEX alerted_imminent_idx (alerted_imminent), INDEX start_idx (start), INDEX end_time_idx (end_time), INDEX new_booking_at_idx (new_booking_at), INDEX created_at_idx (createdAt), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE booking_bank_wire (id INT AUTO_INCREMENT NOT NULL, booking_id INT DEFAULT NULL, user_id INT DEFAULT NULL, status SMALLINT NOT NULL, amount NUMERIC(8, 0) NOT NULL, payed_at DATETIME DEFAULT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, INDEX created_at_bbw_idx (createdAt), INDEX IDX_8929A0B8A76ED395 (user_id), INDEX status_bbw_idx (status), UNIQUE INDEX UNIQ_8929A0B83301C60 (booking_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE booking_payin_refund (id INT AUTO_INCREMENT NOT NULL, booking_id INT DEFAULT NULL, user_id INT DEFAULT NULL, status SMALLINT NOT NULL, amount NUMERIC(8, 0) NOT NULL, payed_at DATETIME DEFAULT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, INDEX created_at_pr_idx (createdAt), INDEX IDX_2CD4E82DA76ED395 (user_id), INDEX status_pr_idx (status), UNIQUE INDEX UNIQ_2CD4E82D3301C60 (booking_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE booking_user_address (id INT AUTO_INCREMENT NOT NULL, booking_id INT DEFAULT NULL, address VARCHAR(255) NOT NULL, city VARCHAR(255) NOT NULL, zip VARCHAR(50) NOT NULL, country VARCHAR(3) NOT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_B7DC90443301C60 (booking_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE categorie (id INT AUTO_INCREMENT NOT NULL, libelle VARCHAR(30) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contact (id BIGINT AUTO_INCREMENT NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, email VARCHAR(1024) NOT NULL, phone VARCHAR(20) DEFAULT NULL, subject VARCHAR(1024) NOT NULL, message LONGTEXT NOT NULL, status SMALLINT NOT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, INDEX created_at_c_idx (createdAt), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE footer (id BIGINT AUTO_INCREMENT NOT NULL, published TINYINT(1) DEFAULT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, INDEX footer_published_idx (published), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE footer_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id BIGINT DEFAULT NULL, url VARCHAR(2000) DEFAULT NULL, url_hash VARCHAR(255) DEFAULT NULL, title VARCHAR(100) NOT NULL, link VARCHAR(2000) NOT NULL, locale VARCHAR(255) NOT NULL, INDEX footer_url_hash_idx (url_hash), INDEX IDX_439793442C2AC5D3 (translatable_id), UNIQUE INDEX footer_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE geo_area (id INT AUTO_INCREMENT NOT NULL, geocoding_id INT DEFAULT NULL, country_id INT DEFAULT NULL, INDEX IDX_D3B31268F92F3E70 (country_id), UNIQUE INDEX UNIQ_D3B312683A405C9 (geocoding_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE geo_area_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(255) DEFAULT NULL, locale VARCHAR(255) NOT NULL, INDEX name_gat_idx (name), INDEX IDX_7A5BDDAB2C2AC5D3 (translatable_id), UNIQUE INDEX geo_area_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE geo_city (id INT AUTO_INCREMENT NOT NULL, geocoding_id INT DEFAULT NULL, department_id INT DEFAULT NULL, area_id INT DEFAULT NULL, country_id INT DEFAULT NULL, INDEX IDX_297C2D34AE80F5DF (department_id), INDEX IDX_297C2D34F92F3E70 (country_id), INDEX IDX_297C2D34BD0F409C (area_id), UNIQUE INDEX UNIQ_297C2D343A405C9 (geocoding_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE geo_city_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(255) DEFAULT NULL, locale VARCHAR(255) NOT NULL, INDEX name_gct_idx (name), INDEX IDX_72D469D42C2AC5D3 (translatable_id), UNIQUE INDEX geo_city_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE geo_coordinate (id INT AUTO_INCREMENT NOT NULL, city_id INT DEFAULT NULL, department_id INT DEFAULT NULL, area_id INT DEFAULT NULL, country_id INT DEFAULT NULL, lat NUMERIC(11, 7) NOT NULL, lng NUMERIC(11, 7) NOT NULL, zip VARCHAR(30) DEFAULT NULL, route VARCHAR(200) DEFAULT NULL, street_number VARCHAR(20) DEFAULT NULL, address VARCHAR(255) NOT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, INDEX IDX_B2E13D99F92F3E70 (country_id), INDEX IDX_B2E13D998BAC62AF (city_id), INDEX IDX_B2E13D99BD0F409C (area_id), INDEX coordinate_idx (lat, lng), INDEX IDX_B2E13D99AE80F5DF (department_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE geo_country (id INT AUTO_INCREMENT NOT NULL, geocoding_id INT DEFAULT NULL, code VARCHAR(3) NOT NULL, INDEX code_idx (code), UNIQUE INDEX UNIQ_E46544643A405C9 (geocoding_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE geo_country_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, name VARCHAR(200) NOT NULL, slug VARCHAR(255) DEFAULT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_F705D5582C2AC5D3 (translatable_id), UNIQUE INDEX geo_country_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE geo_department (id INT AUTO_INCREMENT NOT NULL, geocoding_id INT DEFAULT NULL, area_id INT DEFAULT NULL, country_id INT DEFAULT NULL, INDEX IDX_B4606604F92F3E70 (country_id), INDEX IDX_B4606604BD0F409C (area_id), UNIQUE INDEX UNIQ_B46066043A405C9 (geocoding_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE geo_department_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(255) DEFAULT NULL, locale VARCHAR(255) NOT NULL, INDEX name_gdt_idx (name), INDEX IDX_95DC05742C2AC5D3 (translatable_id), UNIQUE INDEX geo_department_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE geo_geocoding (id INT AUTO_INCREMENT NOT NULL, lat NUMERIC(11, 7) NOT NULL, lng NUMERIC(11, 7) NOT NULL, viewport VARCHAR(100) NOT NULL, address_type VARCHAR(150) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE groupe (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', UNIQUE INDEX UNIQ_6DC044C55E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE image (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lexik_currency (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(3) NOT NULL, rate NUMERIC(10, 4) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE listing (id INT AUTO_INCREMENT NOT NULL, location_id INT DEFAULT NULL, user_id INT DEFAULT NULL, status SMALLINT DEFAULT NULL, type SMALLINT DEFAULT NULL, price NUMERIC(8, 0) NOT NULL, certified TINYINT(1) NOT NULL, min_duration SMALLINT DEFAULT NULL, max_duration SMALLINT DEFAULT NULL, cancellation_policy SMALLINT DEFAULT NULL, average_rating SMALLINT DEFAULT NULL, comment_count INT DEFAULT NULL, admin_notation NUMERIC(3, 1) DEFAULT NULL, availabilities_updated_at DATETIME DEFAULT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, INDEX status_l_idx (status), INDEX min_duration_idx (min_duration), INDEX admin_notation_idx (admin_notation), INDEX IDX_CB0048D4A76ED395 (user_id), INDEX price_idx (price), INDEX max_duration_idx (max_duration), INDEX created_at_l_idx (createdAt), INDEX type_idx (type), INDEX average_rating_idx (average_rating), UNIQUE INDEX UNIQ_CB0048D464D218E (location_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE listing_mariage (listing_id INT NOT NULL, mariage_id INT NOT NULL, INDEX IDX_30D6976DD4619D1A (listing_id), INDEX IDX_30D6976D192813B (mariage_id), PRIMARY KEY(listing_id, mariage_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE listing_listing_category (listing_id INT NOT NULL, listing_category_id INT NOT NULL, INDEX IDX_1AFD54EAD4619D1A (listing_id), INDEX IDX_1AFD54EA455844B0 (listing_category_id), PRIMARY KEY(listing_id, listing_category_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE listing_category (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, texte LONGTEXT DEFAULT NULL, texteaccueil LONGTEXT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, imageaccueil VARCHAR(255) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, description TINYTEXT DEFAULT NULL, accueil TINYINT(1) DEFAULT NULL, lft INT DEFAULT NULL, lvl INT DEFAULT NULL, rgt INT DEFAULT NULL, root INT DEFAULT NULL, INDEX IDX_E0307BBB727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE listing_category_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(255) DEFAULT NULL, locale VARCHAR(255) NOT NULL, INDEX name_idx (name), INDEX IDX_606EDC1F2C2AC5D3 (translatable_id), UNIQUE INDEX listing_category_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE listing_characteristic (id INT AUTO_INCREMENT NOT NULL, listing_characteristic_type_id INT DEFAULT NULL, listing_characteristic_group_id INT DEFAULT NULL, position SMALLINT NOT NULL, INDEX IDX_97E210EC3A0F8087 (listing_characteristic_type_id), INDEX IDX_97E210ECE4714E36 (listing_characteristic_group_id), INDEX position_idx (position), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE listing_characteristic_group (id INT AUTO_INCREMENT NOT NULL, position SMALLINT NOT NULL, UNIQUE INDEX UNIQ_62B4C3E4462CE4F5 (position), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE listing_characteristic_group_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_6C8407162C2AC5D3 (translatable_id), UNIQUE INDEX listing_characteristic_group_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE listing_characteristic_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_945E8F882C2AC5D3 (translatable_id), UNIQUE INDEX listing_characteristic_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE listing_characteristic_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE listing_characteristic_value (id INT AUTO_INCREMENT NOT NULL, listing_characteristic_type_id INT DEFAULT NULL, position SMALLINT NOT NULL, INDEX IDX_1203DF153A0F8087 (listing_characteristic_type_id), INDEX position_lcv_idx (position), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE listing_characteristic_value_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_8BC9A0F42C2AC5D3 (translatable_id), UNIQUE INDEX listing_characteristic_value_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE listing_discount (id INT AUTO_INCREMENT NOT NULL, listing_id INT DEFAULT NULL, discount SMALLINT NOT NULL, from_quantity SMALLINT NOT NULL, INDEX discount_idx (discount), INDEX from_quantity_idx (from_quantity), INDEX IDX_79CD674D4619D1A (listing_id), UNIQUE INDEX discount_unique (listing_id, from_quantity), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE listing_image (id INT AUTO_INCREMENT NOT NULL, listing_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, position SMALLINT NOT NULL, INDEX IDX_33D3DCD3D4619D1A (listing_id), INDEX position_li_idx (position), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE listing_listing_characteristic (id INT AUTO_INCREMENT NOT NULL, listing_characteristic_id INT DEFAULT NULL, listing_id INT DEFAULT NULL, listing_characteristic_value_id INT DEFAULT NULL, INDEX IDX_2FD5B3B6D4619D1A (listing_id), INDEX IDX_2FD5B3B6C27F7D66 (listing_characteristic_id), INDEX IDX_2FD5B3B6E3052CD3 (listing_characteristic_value_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE listing_location (id INT AUTO_INCREMENT NOT NULL, coordinate_id INT DEFAULT NULL, listing_id INT DEFAULT NULL, country VARCHAR(3) NOT NULL, city VARCHAR(75) NOT NULL, zip VARCHAR(20) DEFAULT NULL, route VARCHAR(120) DEFAULT NULL, street_number VARCHAR(20) DEFAULT NULL, INDEX IDX_B8E2EBB198BBE953 (coordinate_id), UNIQUE INDEX UNIQ_B8E2EBB1D4619D1A (listing_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE listing_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, title VARCHAR(50) NOT NULL, description TEXT NOT NULL, rules TEXT DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, locale VARCHAR(255) NOT NULL, INDEX slug_idx (slug), INDEX IDX_E3779C3D2C2AC5D3 (translatable_id), UNIQUE INDEX listing_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mariage (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(40) NOT NULL, texte LONGTEXT DEFAULT NULL, image VARCHAR(255) DEFAULT NULL, traduction VARCHAR(255) DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, imageaccueil VARCHAR(255) DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE message (id INT AUTO_INCREMENT NOT NULL, thread_id INT DEFAULT NULL, sender_id INT DEFAULT NULL, body LONGTEXT NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_B6BD307FE2904019 (thread_id), INDEX IDX_B6BD307FF624B39D (sender_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE message_metadata (id INT AUTO_INCREMENT NOT NULL, message_id INT DEFAULT NULL, participant_id INT DEFAULT NULL, is_read TINYINT(1) NOT NULL, INDEX IDX_4632F005537A1329 (message_id), INDEX IDX_4632F0059D1C3019 (participant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE message_thread (id INT AUTO_INCREMENT NOT NULL, booking_id INT DEFAULT NULL, listing_id INT DEFAULT NULL, subject VARCHAR(255) NOT NULL, createdAt DATETIME NOT NULL, isSpam TINYINT(1) NOT NULL, createdBy_id INT DEFAULT NULL, INDEX IDX_607D18C3174800F (createdBy_id), INDEX IDX_607D18CD4619D1A (listing_id), UNIQUE INDEX UNIQ_607D18C3301C60 (booking_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE message_thread_metadata (id INT AUTO_INCREMENT NOT NULL, participant_id INT DEFAULT NULL, thread_id INT DEFAULT NULL, is_deleted TINYINT(1) NOT NULL, last_participant_message_date DATETIME DEFAULT NULL, last_message_date DATETIME DEFAULT NULL, INDEX IDX_38FC293EE2904019 (thread_id), INDEX IDX_38FC293E9D1C3019 (participant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE page (id BIGINT AUTO_INCREMENT NOT NULL, published TINYINT(1) DEFAULT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, INDEX published_idx (published), INDEX created_at_p_idx (createdAt), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE page_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id BIGINT DEFAULT NULL, meta_title VARCHAR(55) NOT NULL, meta_description TINYTEXT NOT NULL, title VARCHAR(100) NOT NULL, description MEDIUMTEXT NOT NULL, slug VARCHAR(255) DEFAULT NULL, locale VARCHAR(255) NOT NULL, INDEX slug_pt_idx (slug), INDEX IDX_A3D51B1D2C2AC5D3 (translatable_id), UNIQUE INDEX page_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE parameter (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(50) NOT NULL, value VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, INDEX value_idx (value), UNIQUE INDEX UNIQ_2A9791105E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE parameter_audit (id BIGINT NOT NULL, rev INT NOT NULL, name VARCHAR(50) DEFAULT NULL, value VARCHAR(255) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, revtype VARCHAR(4) NOT NULL, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE review (id BIGINT AUTO_INCREMENT NOT NULL, booking_id INT DEFAULT NULL, review_to INT DEFAULT NULL, review_by INT DEFAULT NULL, rating SMALLINT NOT NULL, comment TEXT NOT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, INDEX IDX_794381C63301C60 (booking_id), INDEX created_at_r_idx (createdAt), INDEX IDX_794381C6BEDC2389 (review_by), INDEX IDX_794381C65690230F (review_to), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE revisions (id INT AUTO_INCREMENT NOT NULL, timestamp DATETIME NOT NULL, username VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE theme (id INT AUTO_INCREMENT NOT NULL, header LONGTEXT NOT NULL, footer LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(255) NOT NULL, username_canonical VARCHAR(255) DEFAULT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) DEFAULT NULL, enabled TINYINT(1) DEFAULT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, locked TINYINT(1) DEFAULT NULL, expired TINYINT(1) DEFAULT NULL, expires_at DATETIME DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', credentials_expired TINYINT(1) DEFAULT NULL, credentials_expire_at DATETIME DEFAULT NULL, person_type SMALLINT NOT NULL, company_name VARCHAR(100) DEFAULT NULL, last_name VARCHAR(100) NOT NULL, first_name VARCHAR(100) NOT NULL, phone_prefix VARCHAR(6) DEFAULT NULL, phone VARCHAR(16) DEFAULT NULL, birthday DATE DEFAULT NULL, nationality VARCHAR(3) DEFAULT NULL, country_of_residence VARCHAR(3) DEFAULT NULL, profession VARCHAR(50) NOT NULL, iban VARCHAR(45) DEFAULT NULL, bic VARCHAR(25) DEFAULT NULL, bank_owner_name VARCHAR(100) DEFAULT NULL, bank_owner_address VARCHAR(255) DEFAULT NULL, annual_income NUMERIC(10, 2) DEFAULT NULL, phone_verified TINYINT(1) DEFAULT NULL, email_verified TINYINT(1) DEFAULT NULL, id_card_verified TINYINT(1) DEFAULT NULL, nb_bookings_offerer SMALLINT DEFAULT NULL, nb_bookings_asker SMALLINT DEFAULT NULL, fee_as_asker SMALLINT DEFAULT NULL, fee_as_offerer SMALLINT DEFAULT NULL, average_rating_as_asker SMALLINT DEFAULT NULL, average_rating_as_offerer SMALLINT DEFAULT NULL, mother_tongue VARCHAR(5) DEFAULT NULL, answer_delay INT DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, INDEX slug_u_idx (slug), INDEX enabled_idx (enabled), INDEX created_at_u_idx (createdAt), INDEX email_idx (email), UNIQUE INDEX UNIQ_8D93D64992FC23A8 (username_canonical), UNIQUE INDEX UNIQ_8D93D649A0D96FBF (email_canonical), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_group (user_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_8F02BF9DA76ED395 (user_id), INDEX IDX_8F02BF9DFE54D947 (group_id), PRIMARY KEY(user_id, group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_address (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, type SMALLINT DEFAULT 1, address VARCHAR(255) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, zip VARCHAR(50) DEFAULT NULL, country VARCHAR(3) DEFAULT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, INDEX IDX_5543718BA76ED395 (user_id), INDEX user_address_type_idx (type), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_facebook (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, facebook_id VARCHAR(100) NOT NULL, link VARCHAR(255) NOT NULL, last_name VARCHAR(100) NOT NULL, first_name VARCHAR(100) NOT NULL, birthday DATE DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, verified VARCHAR(100) DEFAULT NULL, location VARCHAR(100) DEFAULT NULL, location_id VARCHAR(100) DEFAULT NULL, hometown VARCHAR(100) DEFAULT NULL, hometown_id VARCHAR(100) DEFAULT NULL, gender VARCHAR(20) DEFAULT NULL, locale VARCHAR(50) DEFAULT NULL, timezone VARCHAR(100) DEFAULT NULL, nb_friends VARCHAR(15) DEFAULT NULL, picture VARCHAR(100) DEFAULT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, INDEX facebook_id_idx (facebook_id), UNIQUE INDEX UNIQ_8BF92CE0A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_image (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, position SMALLINT DEFAULT NULL, INDEX IDX_27FFFF07A76ED395 (user_id), INDEX position_u_idx (position), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_language (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, code VARCHAR(3) NOT NULL, INDEX IDX_345695B5A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_translation (id INT AUTO_INCREMENT NOT NULL, translatable_id INT DEFAULT NULL, description TEXT NOT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_1D728CFA2C2AC5D3 (translatable_id), UNIQUE INDEX user_translation_unique_translation (translatable_id, locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E66BCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (id)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDED4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id)');
        $this->addSql('ALTER TABLE booking_bank_wire ADD CONSTRAINT FK_8929A0B83301C60 FOREIGN KEY (booking_id) REFERENCES booking (id)');
        $this->addSql('ALTER TABLE booking_bank_wire ADD CONSTRAINT FK_8929A0B8A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE booking_payin_refund ADD CONSTRAINT FK_2CD4E82D3301C60 FOREIGN KEY (booking_id) REFERENCES booking (id)');
        $this->addSql('ALTER TABLE booking_payin_refund ADD CONSTRAINT FK_2CD4E82DA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE booking_user_address ADD CONSTRAINT FK_B7DC90443301C60 FOREIGN KEY (booking_id) REFERENCES booking (id)');
        $this->addSql('ALTER TABLE footer_translation ADD CONSTRAINT FK_439793442C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES footer (id)');
        $this->addSql('ALTER TABLE geo_area ADD CONSTRAINT FK_D3B312683A405C9 FOREIGN KEY (geocoding_id) REFERENCES geo_geocoding (id)');
        $this->addSql('ALTER TABLE geo_area ADD CONSTRAINT FK_D3B31268F92F3E70 FOREIGN KEY (country_id) REFERENCES geo_country (id)');
        $this->addSql('ALTER TABLE geo_area_translation ADD CONSTRAINT FK_7A5BDDAB2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES geo_area (id)');
        $this->addSql('ALTER TABLE geo_city ADD CONSTRAINT FK_297C2D343A405C9 FOREIGN KEY (geocoding_id) REFERENCES geo_geocoding (id)');
        $this->addSql('ALTER TABLE geo_city ADD CONSTRAINT FK_297C2D34AE80F5DF FOREIGN KEY (department_id) REFERENCES geo_department (id)');
        $this->addSql('ALTER TABLE geo_city ADD CONSTRAINT FK_297C2D34BD0F409C FOREIGN KEY (area_id) REFERENCES geo_area (id)');
        $this->addSql('ALTER TABLE geo_city ADD CONSTRAINT FK_297C2D34F92F3E70 FOREIGN KEY (country_id) REFERENCES geo_country (id)');
        $this->addSql('ALTER TABLE geo_city_translation ADD CONSTRAINT FK_72D469D42C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES geo_city (id)');
        $this->addSql('ALTER TABLE geo_coordinate ADD CONSTRAINT FK_B2E13D998BAC62AF FOREIGN KEY (city_id) REFERENCES geo_city (id)');
        $this->addSql('ALTER TABLE geo_coordinate ADD CONSTRAINT FK_B2E13D99AE80F5DF FOREIGN KEY (department_id) REFERENCES geo_department (id)');
        $this->addSql('ALTER TABLE geo_coordinate ADD CONSTRAINT FK_B2E13D99BD0F409C FOREIGN KEY (area_id) REFERENCES geo_area (id)');
        $this->addSql('ALTER TABLE geo_coordinate ADD CONSTRAINT FK_B2E13D99F92F3E70 FOREIGN KEY (country_id) REFERENCES geo_country (id)');
        $this->addSql('ALTER TABLE geo_country ADD CONSTRAINT FK_E46544643A405C9 FOREIGN KEY (geocoding_id) REFERENCES geo_geocoding (id)');
        $this->addSql('ALTER TABLE geo_country_translation ADD CONSTRAINT FK_F705D5582C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES geo_country (id)');
        $this->addSql('ALTER TABLE geo_department ADD CONSTRAINT FK_B46066043A405C9 FOREIGN KEY (geocoding_id) REFERENCES geo_geocoding (id)');
        $this->addSql('ALTER TABLE geo_department ADD CONSTRAINT FK_B4606604BD0F409C FOREIGN KEY (area_id) REFERENCES geo_area (id)');
        $this->addSql('ALTER TABLE geo_department ADD CONSTRAINT FK_B4606604F92F3E70 FOREIGN KEY (country_id) REFERENCES geo_country (id)');
        $this->addSql('ALTER TABLE geo_department_translation ADD CONSTRAINT FK_95DC05742C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES geo_department (id)');
        $this->addSql('ALTER TABLE listing ADD CONSTRAINT FK_CB0048D464D218E FOREIGN KEY (location_id) REFERENCES listing_location (id)');
        $this->addSql('ALTER TABLE listing ADD CONSTRAINT FK_CB0048D4A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE listing_mariage ADD CONSTRAINT FK_30D6976DD4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE listing_mariage ADD CONSTRAINT FK_30D6976D192813B FOREIGN KEY (mariage_id) REFERENCES mariage (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE listing_listing_category ADD CONSTRAINT FK_1AFD54EAD4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE listing_listing_category ADD CONSTRAINT FK_1AFD54EA455844B0 FOREIGN KEY (listing_category_id) REFERENCES listing_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE listing_category ADD CONSTRAINT FK_E0307BBB727ACA70 FOREIGN KEY (parent_id) REFERENCES listing_category (id)');
        $this->addSql('ALTER TABLE listing_category_translation ADD CONSTRAINT FK_606EDC1F2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES listing_category (id)');
        $this->addSql('ALTER TABLE listing_characteristic ADD CONSTRAINT FK_97E210EC3A0F8087 FOREIGN KEY (listing_characteristic_type_id) REFERENCES listing_characteristic_type (id)');
        $this->addSql('ALTER TABLE listing_characteristic ADD CONSTRAINT FK_97E210ECE4714E36 FOREIGN KEY (listing_characteristic_group_id) REFERENCES listing_characteristic_group (id)');
        $this->addSql('ALTER TABLE listing_characteristic_group_translation ADD CONSTRAINT FK_6C8407162C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES listing_characteristic_group (id)');
        $this->addSql('ALTER TABLE listing_characteristic_translation ADD CONSTRAINT FK_945E8F882C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES listing_characteristic (id)');
        $this->addSql('ALTER TABLE listing_characteristic_value ADD CONSTRAINT FK_1203DF153A0F8087 FOREIGN KEY (listing_characteristic_type_id) REFERENCES listing_characteristic_type (id)');
        $this->addSql('ALTER TABLE listing_characteristic_value_translation ADD CONSTRAINT FK_8BC9A0F42C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES listing_characteristic_value (id)');
        $this->addSql('ALTER TABLE listing_discount ADD CONSTRAINT FK_79CD674D4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id)');
        $this->addSql('ALTER TABLE listing_image ADD CONSTRAINT FK_33D3DCD3D4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id)');
        $this->addSql('ALTER TABLE listing_listing_characteristic ADD CONSTRAINT FK_2FD5B3B6C27F7D66 FOREIGN KEY (listing_characteristic_id) REFERENCES listing_characteristic (id)');
        $this->addSql('ALTER TABLE listing_listing_characteristic ADD CONSTRAINT FK_2FD5B3B6D4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id)');
        $this->addSql('ALTER TABLE listing_listing_characteristic ADD CONSTRAINT FK_2FD5B3B6E3052CD3 FOREIGN KEY (listing_characteristic_value_id) REFERENCES listing_characteristic_value (id)');
        $this->addSql('ALTER TABLE listing_location ADD CONSTRAINT FK_B8E2EBB198BBE953 FOREIGN KEY (coordinate_id) REFERENCES geo_coordinate (id)');
        $this->addSql('ALTER TABLE listing_location ADD CONSTRAINT FK_B8E2EBB1D4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id)');
        $this->addSql('ALTER TABLE listing_translation ADD CONSTRAINT FK_E3779C3D2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES listing (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FE2904019 FOREIGN KEY (thread_id) REFERENCES message_thread (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FF624B39D FOREIGN KEY (sender_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE message_metadata ADD CONSTRAINT FK_4632F005537A1329 FOREIGN KEY (message_id) REFERENCES message (id)');
        $this->addSql('ALTER TABLE message_metadata ADD CONSTRAINT FK_4632F0059D1C3019 FOREIGN KEY (participant_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE message_thread ADD CONSTRAINT FK_607D18C3174800F FOREIGN KEY (createdBy_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE message_thread ADD CONSTRAINT FK_607D18C3301C60 FOREIGN KEY (booking_id) REFERENCES booking (id)');
        $this->addSql('ALTER TABLE message_thread ADD CONSTRAINT FK_607D18CD4619D1A FOREIGN KEY (listing_id) REFERENCES listing (id)');
        $this->addSql('ALTER TABLE message_thread_metadata ADD CONSTRAINT FK_38FC293E9D1C3019 FOREIGN KEY (participant_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE message_thread_metadata ADD CONSTRAINT FK_38FC293EE2904019 FOREIGN KEY (thread_id) REFERENCES message_thread (id)');
        $this->addSql('ALTER TABLE page_translation ADD CONSTRAINT FK_A3D51B1D2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES page (id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C63301C60 FOREIGN KEY (booking_id) REFERENCES booking (id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C65690230F FOREIGN KEY (review_to) REFERENCES user (id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6BEDC2389 FOREIGN KEY (review_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_group ADD CONSTRAINT FK_8F02BF9DA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_group ADD CONSTRAINT FK_8F02BF9DFE54D947 FOREIGN KEY (group_id) REFERENCES groupe (id)');
        $this->addSql('ALTER TABLE user_address ADD CONSTRAINT FK_5543718BA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_facebook ADD CONSTRAINT FK_8BF92CE0A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_image ADD CONSTRAINT FK_27FFFF07A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_language ADD CONSTRAINT FK_345695B5A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_translation ADD CONSTRAINT FK_1D728CFA2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES user (id)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE booking_bank_wire DROP FOREIGN KEY FK_8929A0B83301C60');
        $this->addSql('ALTER TABLE booking_payin_refund DROP FOREIGN KEY FK_2CD4E82D3301C60');
        $this->addSql('ALTER TABLE booking_user_address DROP FOREIGN KEY FK_B7DC90443301C60');
        $this->addSql('ALTER TABLE message_thread DROP FOREIGN KEY FK_607D18C3301C60');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C63301C60');
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY FK_23A0E66BCF5E72D');
        $this->addSql('ALTER TABLE footer_translation DROP FOREIGN KEY FK_439793442C2AC5D3');
        $this->addSql('ALTER TABLE geo_area_translation DROP FOREIGN KEY FK_7A5BDDAB2C2AC5D3');
        $this->addSql('ALTER TABLE geo_city DROP FOREIGN KEY FK_297C2D34BD0F409C');
        $this->addSql('ALTER TABLE geo_coordinate DROP FOREIGN KEY FK_B2E13D99BD0F409C');
        $this->addSql('ALTER TABLE geo_department DROP FOREIGN KEY FK_B4606604BD0F409C');
        $this->addSql('ALTER TABLE geo_city_translation DROP FOREIGN KEY FK_72D469D42C2AC5D3');
        $this->addSql('ALTER TABLE geo_coordinate DROP FOREIGN KEY FK_B2E13D998BAC62AF');
        $this->addSql('ALTER TABLE listing_location DROP FOREIGN KEY FK_B8E2EBB198BBE953');
        $this->addSql('ALTER TABLE geo_area DROP FOREIGN KEY FK_D3B31268F92F3E70');
        $this->addSql('ALTER TABLE geo_city DROP FOREIGN KEY FK_297C2D34F92F3E70');
        $this->addSql('ALTER TABLE geo_coordinate DROP FOREIGN KEY FK_B2E13D99F92F3E70');
        $this->addSql('ALTER TABLE geo_country_translation DROP FOREIGN KEY FK_F705D5582C2AC5D3');
        $this->addSql('ALTER TABLE geo_department DROP FOREIGN KEY FK_B4606604F92F3E70');
        $this->addSql('ALTER TABLE geo_city DROP FOREIGN KEY FK_297C2D34AE80F5DF');
        $this->addSql('ALTER TABLE geo_coordinate DROP FOREIGN KEY FK_B2E13D99AE80F5DF');
        $this->addSql('ALTER TABLE geo_department_translation DROP FOREIGN KEY FK_95DC05742C2AC5D3');
        $this->addSql('ALTER TABLE geo_area DROP FOREIGN KEY FK_D3B312683A405C9');
        $this->addSql('ALTER TABLE geo_city DROP FOREIGN KEY FK_297C2D343A405C9');
        $this->addSql('ALTER TABLE geo_country DROP FOREIGN KEY FK_E46544643A405C9');
        $this->addSql('ALTER TABLE geo_department DROP FOREIGN KEY FK_B46066043A405C9');
        $this->addSql('ALTER TABLE user_group DROP FOREIGN KEY FK_8F02BF9DFE54D947');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDED4619D1A');
        $this->addSql('ALTER TABLE listing_mariage DROP FOREIGN KEY FK_30D6976DD4619D1A');
        $this->addSql('ALTER TABLE listing_listing_category DROP FOREIGN KEY FK_1AFD54EAD4619D1A');
        $this->addSql('ALTER TABLE listing_discount DROP FOREIGN KEY FK_79CD674D4619D1A');
        $this->addSql('ALTER TABLE listing_image DROP FOREIGN KEY FK_33D3DCD3D4619D1A');
        $this->addSql('ALTER TABLE listing_listing_characteristic DROP FOREIGN KEY FK_2FD5B3B6D4619D1A');
        $this->addSql('ALTER TABLE listing_location DROP FOREIGN KEY FK_B8E2EBB1D4619D1A');
        $this->addSql('ALTER TABLE listing_translation DROP FOREIGN KEY FK_E3779C3D2C2AC5D3');
        $this->addSql('ALTER TABLE message_thread DROP FOREIGN KEY FK_607D18CD4619D1A');
        $this->addSql('ALTER TABLE listing_listing_category DROP FOREIGN KEY FK_1AFD54EA455844B0');
        $this->addSql('ALTER TABLE listing_category DROP FOREIGN KEY FK_E0307BBB727ACA70');
        $this->addSql('ALTER TABLE listing_category_translation DROP FOREIGN KEY FK_606EDC1F2C2AC5D3');
        $this->addSql('ALTER TABLE listing_characteristic_translation DROP FOREIGN KEY FK_945E8F882C2AC5D3');
        $this->addSql('ALTER TABLE listing_listing_characteristic DROP FOREIGN KEY FK_2FD5B3B6C27F7D66');
        $this->addSql('ALTER TABLE listing_characteristic DROP FOREIGN KEY FK_97E210ECE4714E36');
        $this->addSql('ALTER TABLE listing_characteristic_group_translation DROP FOREIGN KEY FK_6C8407162C2AC5D3');
        $this->addSql('ALTER TABLE listing_characteristic DROP FOREIGN KEY FK_97E210EC3A0F8087');
        $this->addSql('ALTER TABLE listing_characteristic_value DROP FOREIGN KEY FK_1203DF153A0F8087');
        $this->addSql('ALTER TABLE listing_characteristic_value_translation DROP FOREIGN KEY FK_8BC9A0F42C2AC5D3');
        $this->addSql('ALTER TABLE listing_listing_characteristic DROP FOREIGN KEY FK_2FD5B3B6E3052CD3');
        $this->addSql('ALTER TABLE listing DROP FOREIGN KEY FK_CB0048D464D218E');
        $this->addSql('ALTER TABLE listing_mariage DROP FOREIGN KEY FK_30D6976D192813B');
        $this->addSql('ALTER TABLE message_metadata DROP FOREIGN KEY FK_4632F005537A1329');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307FE2904019');
        $this->addSql('ALTER TABLE message_thread_metadata DROP FOREIGN KEY FK_38FC293EE2904019');
        $this->addSql('ALTER TABLE page_translation DROP FOREIGN KEY FK_A3D51B1D2C2AC5D3');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDEA76ED395');
        $this->addSql('ALTER TABLE booking_bank_wire DROP FOREIGN KEY FK_8929A0B8A76ED395');
        $this->addSql('ALTER TABLE booking_payin_refund DROP FOREIGN KEY FK_2CD4E82DA76ED395');
        $this->addSql('ALTER TABLE listing DROP FOREIGN KEY FK_CB0048D4A76ED395');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307FF624B39D');
        $this->addSql('ALTER TABLE message_metadata DROP FOREIGN KEY FK_4632F0059D1C3019');
        $this->addSql('ALTER TABLE message_thread DROP FOREIGN KEY FK_607D18C3174800F');
        $this->addSql('ALTER TABLE message_thread_metadata DROP FOREIGN KEY FK_38FC293E9D1C3019');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C65690230F');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6BEDC2389');
        $this->addSql('ALTER TABLE user_group DROP FOREIGN KEY FK_8F02BF9DA76ED395');
        $this->addSql('ALTER TABLE user_address DROP FOREIGN KEY FK_5543718BA76ED395');
        $this->addSql('ALTER TABLE user_facebook DROP FOREIGN KEY FK_8BF92CE0A76ED395');
        $this->addSql('ALTER TABLE user_image DROP FOREIGN KEY FK_27FFFF07A76ED395');
        $this->addSql('ALTER TABLE user_language DROP FOREIGN KEY FK_345695B5A76ED395');
        $this->addSql('ALTER TABLE user_translation DROP FOREIGN KEY FK_1D728CFA2C2AC5D3');
        $this->addSql('DROP TABLE article');
        $this->addSql('DROP TABLE booking');
        $this->addSql('DROP TABLE booking_bank_wire');
        $this->addSql('DROP TABLE booking_payin_refund');
        $this->addSql('DROP TABLE booking_user_address');
        $this->addSql('DROP TABLE categorie');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE footer');
        $this->addSql('DROP TABLE footer_translation');
        $this->addSql('DROP TABLE geo_area');
        $this->addSql('DROP TABLE geo_area_translation');
        $this->addSql('DROP TABLE geo_city');
        $this->addSql('DROP TABLE geo_city_translation');
        $this->addSql('DROP TABLE geo_coordinate');
        $this->addSql('DROP TABLE geo_country');
        $this->addSql('DROP TABLE geo_country_translation');
        $this->addSql('DROP TABLE geo_department');
        $this->addSql('DROP TABLE geo_department_translation');
        $this->addSql('DROP TABLE geo_geocoding');
        $this->addSql('DROP TABLE groupe');
        $this->addSql('DROP TABLE image');
        $this->addSql('DROP TABLE lexik_currency');
        $this->addSql('DROP TABLE listing');
        $this->addSql('DROP TABLE listing_mariage');
        $this->addSql('DROP TABLE listing_listing_category');
        $this->addSql('DROP TABLE listing_category');
        $this->addSql('DROP TABLE listing_category_translation');
        $this->addSql('DROP TABLE listing_characteristic');
        $this->addSql('DROP TABLE listing_characteristic_group');
        $this->addSql('DROP TABLE listing_characteristic_group_translation');
        $this->addSql('DROP TABLE listing_characteristic_translation');
        $this->addSql('DROP TABLE listing_characteristic_type');
        $this->addSql('DROP TABLE listing_characteristic_value');
        $this->addSql('DROP TABLE listing_characteristic_value_translation');
        $this->addSql('DROP TABLE listing_discount');
        $this->addSql('DROP TABLE listing_image');
        $this->addSql('DROP TABLE listing_listing_characteristic');
        $this->addSql('DROP TABLE listing_location');
        $this->addSql('DROP TABLE listing_translation');
        $this->addSql('DROP TABLE mariage');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE message_metadata');
        $this->addSql('DROP TABLE message_thread');
        $this->addSql('DROP TABLE message_thread_metadata');
        $this->addSql('DROP TABLE page');
        $this->addSql('DROP TABLE page_translation');
        $this->addSql('DROP TABLE parameter');
        $this->addSql('DROP TABLE parameter_audit');
        $this->addSql('DROP TABLE review');
        $this->addSql('DROP TABLE revisions');
        $this->addSql('DROP TABLE theme');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE user_group');
        $this->addSql('DROP TABLE user_address');
        $this->addSql('DROP TABLE user_facebook');
        $this->addSql('DROP TABLE user_image');
        $this->addSql('DROP TABLE user_language');
        $this->addSql('DROP TABLE user_translation');
    }
}
